joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

joy_teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 3.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.875

    enable_button: 5
    # inverted_reverse: true
    require_enable_button: true    