controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:

    front_steering: true
    rear_wheels_names: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
    front_wheels_names: ['front_left_steering_joint', 'front_right_steering_joint']
    
    wheelbase: 0.5
    front_wheel_track: 0.3
    rear_wheel_track: 0.3
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1
    
    reference_timeout: 2.0
    velocity_rolling_window_size: 10

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    use_stamped_vel: true

    open_loop: true
    position_feedback: false

    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]