controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController


bicycle_steering_controller:
  ros__parameters:
    wheelbase: 1.197
    front_wheel_radius: 0.225
    rear_wheel_radius: 0.225
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['virtual_rear_wheel_joint']
    front_wheels_names: ['virtual_front_wheel_joint']
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    open_loop: false
    position_feedback: true
    use_stamped_vel: true
