ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true
 
        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_footprint 
        world_frame: odom 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        # odom0: odom/unfiltered
        # odom0_config: [false, false, false,
        #                false, false, false,
        #                true, true, false,
        #                false, false, true,
        #                false, false, false]

        # imu0: imu/data
        # imu0_config: [false, false, false,
        #                 true, true, true,
        #                 false, false, false,
        #                 true, true, true,
        #                 false, false, false]
        # imu0_differential: false
        # imu0_relative: false
        # imu0_queue_size: 5
        # imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
        # imu0_twist_rejection_threshold: 0.8                #
        # imu0_linear_acceleration_rejection_threshold: 0.8  #
        
        pose0: /pcl_pose
        pose0_config: [true,  true,  true,
                       true, true, true,
                       true, true, true,
                       true, true, true,
                       true, true, true]
        # pose0_differential: true
        # pose0_relative: false
        # pose0_queue_size: 5
        # pose0_rejection_threshold: 2.0  # Note the difference in parameter name