<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="delicar" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931" />
    <xacro:property name="base_mass" value="50.0" />
    <xacro:property name="base_width" value="1" />
    <xacro:property name="base_length" value="1.6" />
    <xacro:property name="base_height" value="0.4" />
    <xacro:property name="wheelbase" value="1.2" />
    <xacro:property name="wheeltrack" value="1.0" />
    <xacro:property name="wheel_mass" value="5" />
    <xacro:property name="wheel_len" value="0.1" />
    <xacro:property name="wheel_radius" value="0.225" />


    <!-- Base Link -->
    <link name="${prefix}base_link" />

    <!-- Chassis -->
    <link name="${prefix}chassis_link">

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
        <material name="red">
          <color rgba="1.0 0.2 0.2 1.0" />
        </material>
      </visual>

      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}" />
        </geometry>
      </collision> -->

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${base_mass}" />
        <inertia
          ixx="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}"
          iyz="0.0"
          izz="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}" />
      </inertial>

    </link>

    <!-- Fix color bug in gazebo -->
    <gazebo reference="${prefix}chassis_link">
      <visual>
        <material>
          <ambient>1.0 0.2 0.2 1.0</ambient>
          <diffuse>1.0 0.2 0.2 1.0</diffuse>
          <specular>1.0 1.0 1.0 1.0</specular>
          <emissive>0.2 0.0 0.0 1.0</emissive>
        </material>
      </visual>
    </gazebo>

    <!-- Chassis Joint -->
    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}chassis_link" />
      <origin xyz="0 0 ${wheel_radius + base_height/2}" rpy="0 0 0" />
    </joint>


    <!-- Rear wheels -->

    <!-- rear left wheel -->
    <link name="${prefix}rear_left_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0" />
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}" />
      </inertial>
    </link>

    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}rear_left_wheel" />
      <origin xyz="-${wheelbase/2} ${wheeltrack/2} -${base_height/2}" rpy="-1.57 0 0" />
      <axis xyz="0 0 1" />
      <limit effort="1000.0" velocity="100" />
    </joint>

    <gazebo reference="${prefix}rear_left_wheel">
      <visual>
        <material>
          <ambient>0.0 0.0 0.0 1.0</ambient>
          <diffuse>0.0 0.0 0.0 1.0</diffuse>
          <specular>0.5 0.5 0.5 1.0</specular>
          <emissive>0.0 0.0 0.0 1.0</emissive>
        </material>
      </visual>
    </gazebo>

    <!-- rear right wheel -->

    <link name="${prefix}rear_right_wheel">

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black">
          <color rgba="0.0 0.0 0.0 1.0" />
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}" />
      </inertial>

    </link>

    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}rear_right_wheel" />
      <origin xyz="-${wheelbase/2} -${wheeltrack/2} -${base_height/2}" rpy="-1.57 0 0" />
      <axis xyz="0 0 1" />
      <limit effort="1000.0" velocity="100" />
    </joint>

    <gazebo reference="${prefix}rear_right_wheel">
      <visual>
        <material>
          <ambient>0.0 0.0 0.0 1.0</ambient>
          <diffuse>0.0 0.0 0.0 1.0</diffuse>
          <specular>0.5 0.5 0.5 1.0</specular>
          <emissive>0.0 0.0 0.0 1.0</emissive>
        </material>
      </visual>
    </gazebo>

    <!-- steering links-->

    <!-- left sterring link-->

    <link name="${prefix}left_wheel_steering">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <!-- left sterring joint-->

    <joint name="${prefix}left_wheel_steering_joint" type="revolute">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}left_wheel_steering" />
      <origin xyz="${wheelbase/2} -${wheeltrack/2} -${base_height/2}" rpy="${PI/2} 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="1000.0" lower="-1.0471975512" upper="1.0471975512" velocity="30" />
    </joint>

    <!-- right sterring link-->

    <link name="${prefix}right_wheel_steering">
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <!-- right sterring joint-->

    <joint name="${prefix}right_wheel_steering_joint" type="revolute">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}right_wheel_steering" />
      <origin xyz="${wheelbase/2} ${wheeltrack/2} -${base_height/2}" rpy="${PI/2} 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="1000.0" lower="-1.0471975512" upper="1.0471975512" velocity="30" />
    </joint>

    <!-- front wheels -->

    <!-- front left steering -->

    <link name="${prefix}front_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}" />
      </inertial>

    </link>

    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}left_wheel_steering" />
      <child link="${prefix}front_left_wheel" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- front right wheel -->

    <link name="${prefix}front_right_wheel">

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}" />
        </geometry>
        <material name="black" />
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          ixy="0.0"
          ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3 * wheel_radius*wheel_radius + wheel_len*wheel_len)}"
          iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}" />
      </inertial>
    </link>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}right_wheel_steering" />
      <child link="${prefix}front_right_wheel" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
    </joint>

    <!-- lidar base -->

    <link name="${prefix}lidar_base">

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.03" radius="0.0525" />
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia
          ixx="0.01"
          ixy="0.0"
          ixz="0.0"
          iyy="0.01"
          iyz="0.0"
          izz="0.01" />
      </inertial>
    </link>

    <joint name="${prefix}lidar_base_joint" type="fixed">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}lidar_base" />
      <origin xyz="0.6 0 0.2" rpy="0 0 0" />
    </joint>

  </xacro:macro>

</robot>