/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 1.5
      ndt_resolution: 0.5
      ndt_step_size: 0.05
      ndt_num_threads: 0
      transform_epsilon: 0.01
      voxel_leaf_size: 0.2
      scan_max_range: 50.0
      scan_min_range: 0.5
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/zuntes/lidar_slam_ws/src/lidar_localization_ros2/maps/map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      use_imu: false
      enable_debug: false
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link
