bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "uart"
    uart_port: "/dev/ttyUSB0"
    uart_baudrate: 115200
    uart_timeout: 0.1
    data_query_frequency: 100
    calib_status_frequency: 0.1
    frame_id: "imu_link"
    # Use ACCONLY mode so the accelerometer output includes gravity
    operation_mode: 0x0C
    # Set axis remap so that the sensor's Z-axis points vertically (default is "P1")
    placement_axis_remap: "P1"
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    grav_factor: 100.0
    set_offsets: false  # or true if you are restoring saved calibration offsets
    offset_acc: [0xFFEC, 0x00A5, 0xFFE8]
    offset_mag: [0xFFB4, 0xFE9E, 0x027D]
    offset_gyr: [0x0002, 0xFFFF, 0xFFFF]
